FROM rust:1.66-slim AS builder

WORKDIR /build

COPY . ./

RUN cd gen-forge-updates; cargo build --release --locked

# something.. something.. tls issues with musl, so we cant use it and thus cant use scratch/alpine
FROM debian:stable-slim
COPY --from=builder /build/target/release/gen-forge-updates /bin/gen-forge-updates
ENTRYPOINT ["/bin/gen-forge-updates"]
