FROM rust:1.66-slim AS builder

RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /build

COPY . ./

RUN cd extract; cargo build --release --locked --target x86_64-unknown-linux-musl

FROM scratch
COPY --from=builder /build/target/x86_64-unknown-linux-musl/release/extract /bin/extract
ENTRYPOINT ["/bin/extract"]
