name: Generate Forge Updates
author: necauqua
description: Renders the extracted changelog JSON into a Forge updates.json file
inputs:
  changelog:
    description: Input changelog JSON file
    required: true
    default: changelog.json
  filename:
    description: Resulting JSON file name
    required: true
    default: updates.json
  template:
    description: JSON template file with predefined values etc.
    required: false
runs:
  using: docker
  image: docker://ghcr.io/necauqua/changelogs@sha256:d82b558f7b97f1755ff6c86372f313cc552edcc44512c262d5a9d7228716abc4
  args:
    - gen-forge-updates
    - ${{ inputs.changelog }}
    - ${{ inputs.filename }}
    - ${{ inputs.template }}
