name: Generate Forge Updates
author: necauqua
description: Renders the extracted changelog JSON into a Forge updates.json file
inputs:
  changelog:
    description: Input changelog JSON file
    required: true
    default: changelog.json
  filename:
    description: Resulting JSON file name
    required: true
    default: updates.json
  template:
    description: JSON template file with predefined values etc.
    required: false
runs:
  using: docker
  image: docker://ghcr.io/necauqua/changelogs@sha256:2880e15524b50e1a928356eec85cc00b9288fb50bb0191abd08f8db58abe96d3
  args:
    - ${{ inputs.filename }}
    - gen-forge-updates
    - ${{ inputs.changelog }}
    - ${{ inputs.template }}
