name: Generate Forge Updates
author: necauqua
description: Renders the extracted changelog JSON into a Forge updates.json file
inputs:
  changelog:
    description: Input changelog JSON file
    required: true
    default: changelog.json
  filename:
    description: Resulting JSON file name
    required: true
    default: updates.json
  template:
    description: JSON template file with predefined values etc.
    required: false
runs:
  using: docker
  image: docker://ghcr.io/necauqua/changelogs@sha256:cec28af906511eaa1f6f650fb3aa4a211d332f72fd6f86fd8a80ce372dcf1bc7
  args:
    - ${{ inputs.filename }}
    - gen-forge-updates
    - ${{ inputs.changelog }}
    - ${{ inputs.template }}
