name: Extract Changelog
author: necauqua
description: Exctract changelog from approproately formatted git commit bodies
inputs:
  root-commit:
    description: The commit starting from the children of which the log will be extracted
    required: false
  filename:
    description: Name of the file that will contain the generated JSON changelog
    default: changelog.json
    required: true
runs:
  using: docker
  image: docker://ghcr.io/necauqua/changelogs@sha256:cec28af906511eaa1f6f650fb3aa4a211d332f72fd6f86fd8a80ce372dcf1bc7
  args:
    - ${{ inputs.filename }}
    - extract
    - ${{ inputs.root-commit }}
