name: Extract Changelog
author: necauqua
description: Exctract changelog from approproately formatted git commit bodies
inputs:
  root-commit:
    description: The commit from whose children the log will be extracted
    required: false
  filename:
    description: Name of the file that will contain the generated JSON changelog
    default: changelog.json
    required: true
runs:
  using: docker
  image: docker://ghcr.io/necauqua/changelogs@sha256:1d3974cb22f114886e2ae9caa720d434fc6e44687cd8b37ee58545e62c60ca3e
  args:
    - extract
    - ${{ inputs.filename }}
    - ${{ inputs.root-commit }}
