name: Render Changelog
author: necauqua
description: Renders the extracted changelog JSON into markdown
inputs:
  changelog:
    description: Input changelog JSON
    default: changelog.json
  tag-format:
    description: Format of the release header
    default: '[[[{tag}](https://github.com/${{ github.repository }}/tree/{tag})]] {timestamp}'
  date-format:
    description: Format of the date used in tag format
    default: '%F'
  issue-format:
    description: If non-empty, replaces all occurences of `#<number>` with a link with given format
    default: '[#{number}](https://github.com/${{ github.repository }}/issues/{number})'
  unreleased-header:
    description: Unreleased header string
    default: Unreleased ([{short_hash}](https://github.com/${{ github.repository }}/tree/{hash}))
  filename:
    description: Resulting markdown file name
    default: changelog.md
  only-last:
    description: Set to true to only write the last changelog (unreleased or last release if unreleased is empty) without a header. Ignores the template and header settings
    default: "false"
  template:
    description: Changelog template file
runs:
  using: docker
  image: docker://ghcr.io/necauqua/changelogs@sha256:406b9f2b327e02cf2bf4805299bc1065db1d6bd0ba2f286335835346ef0a2415
  args:
    - render
    - ${{ inputs.changelog }}
    - ${{ inputs.tag-format }}
    - ${{ inputs.date-format }}
    - ${{ inputs.issue-format }}
    - ${{ inputs.unreleased-header }}
    - ${{ inputs.filename }}
    - ${{ inputs.only-last }}
    - ${{ inputs.template }}

