[package]
name = 'render'
version = '0.1.0'
edition = '2021'
publish = false

[dependencies]
anyhow = '1.0.68'
chrono = { version = '0.4.23', default-features = false, features = ['alloc'] }
serde_json = '1.0.91'

extract = { path = '../extract' }
